name: Hello workflow
on: 
  push: {}
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      run: |
        echo "Hello Github Actions"
        echo "${{ github.ref }}"
        echo "Branch Name ID ${{ github.sha }}"
