name: Task 4 - Matrix
on:
  push
jobs:
  matrix-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node
        uses: actions /setup-node@v7
        with:
          node-version: ${{ matrix.node }}
      - name: Print matrix
        run: echo "OS= ${{ matrix.os }} Node=${{ matrix.node }}"

    