name: Hello workflow
on: 
  push: {}
jobs:
  veerabadra:
    runs-on: ubuntu-latest
    steps:
      - name: Veeresh step1
        run: |
          echo "Hello Github Actions"
          echo "${{ github.ref }}"
          echo "Branch Name ID ${{ github.sha }}"
      
      - name: Veeresh2 step2
        run: |
          echo "Hello Github Actions"
          echo "${{ github.ref }}"
          echo "Branch Name ID ${{ github.sha }}"

      - name: Veeresh3 step3
        run: |
          echo "Hello Github Actions"
          echo "${{ github.ref }}"
          echo "Branch Name ID ${{ github.sha }}"
