name: Hello workflow
on: 
  push: {}
jobs:
  veerabadra:
    runs-on: ubuntu-latest
    steps:
      - name: Veeresh step1
        run: |
          echo "Hello Github Actions"
          echo "${{ github.ref }}"
          echo "Branch Name ID ${{ github.sha }}"