name: Task 3 - Multi Step

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      
      - name: Show files
        run : ls -la
      
      - name: Show README content
        run: cat README.md

      - name: Simulate build
        run: echo "Building..."